export const LOGIN_USER = 'LOGIN_USER'
export const USER_DATA = 'USER_DATA'

// user
export const ALT_TRANSACTION_LISTS = 'ALT_TRANSACTION_LISTS'
export const ALT_NOTIFICATION = 'ALT_NOTIFICATION'
export const ALT_REQUEST_LISTS = 'ALT_REQUEST_LISTS'
export const ALT_CATELOG = 'ALT_CATELOG'
export const ALT_GIFT_LISTS = 'ALT_GIFT_LISTS'
export const LOGOUT_USER = 'LOGOUT_USER'

// App
export const ALT_DATA_PLAN = 'ALT_DATA_PLAN'
