const TYPES = {
  LOGIN_USER: "LOGIN_USER",
  USER_DATA: "USER_DATA",

  // user
  ALT_TRANSACTION_LISTS: "ALT_TRANSACTION_LISTS",
  ALT_NOTIFICATION: "ALT_NOTIFICATION",
  ALT_REQUEST_LISTS: "ALT_REQUEST_LISTS",
  ALT_CATELOG: "ALT_CATELOG",
  ALT_GIFT_LISTS: "ALT_GIFT_LISTS",
  LOGOUT_USER: "LOGOUT_USER",
  ALT_CARDLISTS: "ALT_CARDLISTS",
  ALT_PERSONALBANK_INFO: "ALT_PERSONALBANK_INFO",
  ALT_VIRTUAL_CARDS_LISTS: "ALT_VIRTUAL_CARDS_LISTS",

  // App
  ALT_DATA_PLAN: "ALT_DATA_PLAN",
};

export default TYPES;
